<?php

namespace ComfinyMeliBlueBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    function find10LastPosts(){
        return $this
            ->createQueryBuilder('p')
            ->orderBy('p.createdAt','DESC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
            ;
    }


    function findPostsPerPage($page, $nbPerPage){

           $query = $this->createQueryBuilder('p')
            ->orderBy('p.createdAt','DESC')
            ->getQuery()
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }

}
