<?php

namespace ComfinyMeliBlueBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    function find10LastPosts(){
        return $this
            ->createQueryBuilder('p')
            ->orderBy('p.createdAt','DESC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
            ;
    }

}
